<div align="left" style="background-color: #008080; padding: 20px 10px;">
<h3><b>IDEAS - Institute of Data Engineering, Analytics and Science Foundation</b></h3>
<p>Summer Internship Program 2026</p>
<hr style="width:100%;">
<h3><b>Project Title:</b> Student Academic Performance Prediction</h3>
<h4>Project Notebook</h4>

<blockquote style="border-left: 4px solid #4285F4; padding-left: 15px;">
  <strong>Created by:</strong> Adrija Das<br>
  <strong>Designation:</strong> Project Linked Associate Research Engineer
</blockquote>
<hr style="width:100%;">
</div>

### Question 1: Data Loading (2 Marks)
Download `student_performance_dataset.csv` dataset from https://www.kaggle.com/datasets/aiexplorer77/academic-performance-prediction. Import pandas and load the dataset. Print the first 5 rows of the DataFrame.

**Expected Output:**
```
A pandas DataFrame displaying the first 5 rows of the dataset.
```

In [3]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [31]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/student_performance_dataset.csv")
df.head()

,student_id,age,gender,city_type,study_hours_per_day,deep_work_sessions,assignment_completion_rate,attendance_percentage,social_media_hours,doomscrolling_before_sleep,...,family_support,financial_stress,learning_style,career_goal,productivity_after_midnight,revision_efficiency,burnout_risk,consistency_score,final_exam_score,performance_category
0,0,21,Female,Semi-Urban,3.2,7,100,70,3.8,0,...,10,6,Audio,Engineering,9,1,10,3,32,Low
1,1,19,Female,Semi-Urban,3.9,2,46,70,2.6,1,...,2,6,Practical,Business,6,10,4,6,59,Medium
2,2,16,Female,Urban,4.3,7,54,57,4.3,1,...,1,9,Visual,Engineering,7,9,8,1,34,Low
3,3,19,Male,Semi-Urban,5.3,1,78,90,1.7,0,...,5,10,Reading,Medical,7,7,9,10,60,Medium
4,4,17,Female,Urban,4.1,3,100,81,2.6,0,...,5,6,Visual,Medical,4,10,7,9,77,High

### Question 2: Identify Column Types (2 Marks)
Identify and print the list of numerical and categorical column names in the dataset.

**Expected Output:**
```
Lists of numerical and categorical column names.
```

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   student_id                   3000 non-null   int64
 1   age                          3000 non-null   int64
 2   gender                       3000 non-null   object
 3   city_type                    3000 non-null   object
 4   study_hours_per_day          3000 non-null   float64
 5   deep_work_sessions           3000 non-null   int64
 6   assignment_completion_rate   3000 non-null   int64
 7   attendance_percentage        3000 non-null   int64
 8   social_media_hours           2940 non-null   float64
 9   doomscrolling_before_sleep   3000 non-null   int64
 10  notification_distractions    3000 non-null   int64
 11  ai_tool_usage_hours          3000 non-null   float64
 12  gaming_hours                 3000 non-null   float64
 13  stress_level                 3000 non-null   int64
 14  motivation_level             3000 non-null   int64
 15  focus_score                  2940 non-null   float64
 16  procrastination_index        3000 non-null   int64
 17  mental_state                 3000 non-null   object
 18  sleep_hours                  2940 non-null   float64
 19  caffeine_intake              3000 non-null   int64
 20  physical_activity_hours      3000 non-null   float64
 21  internet_quality             3000 non-null   int64
 22  family_support               3000 non-null   int64
 23  financial_stress             3000 non-null   int64
 24  learning_style               3000 non-null   object
 25  career_goal                  3000 non-null   object
 26  productivity_after_midnight  3000 non-null   int64
 27  revision_efficiency          3000 non-null   int64
 28  burnout_risk                 3000 non-null   int64
 29  consistency_score            3000 non-null   int64
 30  final_exam_score             3000 non-null   int64
 31  performance_category         3000 non-null   object
dtypes: float64(7), int64(19), object(6)
memory usage: 750.1+ KB

### Question 3: Missing Values (2 Marks)
Check for missing values in the dataset and print the sum of missing values for each column.

**Expected Output:**
```

In [32]:
df.isnull().sum()

student_id                      0
age                             0
gender                          0
city_type                       0
study_hours_per_day             0
deep_work_sessions              0
assignment_completion_rate      0
attendance_percentage           0
social_media_hours             60
doomscrolling_before_sleep      0
notification_distractions       0
ai_tool_usage_hours             0
gaming_hours                    0
stress_level                    0
motivation_level                0
focus_score                    60
procrastination_index           0
mental_state                    0
sleep_hours                    60
caffeine_intake                 0
physical_activity_hours         0
internet_quality                0
family_support                  0
financial_stress                0
learning_style                  0
career_goal                     0
productivity_after_midnight     0
revision_efficiency             0
burnout_risk                    0
consistency_score               0
final_exam_score                0
performance_category            0
dtype: int64

### Question 4: Data Imputation (3 Marks)
Fill missing numerical values with the median and missing categorical values with the mode. Print the total number of missing values remaining in the entire dataset.

In [36]:
#from sklearn importing Simple Imputer class
from sklearn.impute import SimpleImputer
imputer_median = SimpleImputer(strategy="median")   #for numerical
imputer_mode = SimpleImputer(strategy="most_frequent")  #for categorical

#Selecting numerical and categorical columns seperately
df_num = df.select_dtypes(include = "number")
df_cat = df.select_dtypes(exclude= "number")

#using .fit_transform
num_impute = imputer_median.fit_transform(df_num)
cat_impute = imputer_mode.fit_transform(df_cat)

#Converting to dataframe
df_num_impute = pd.DataFrame(data = num_impute, columns = df_num.columns)
df_cat_impute =  pd.DataFrame(data = cat_impute, columns = df_cat.columns)

#Concatenating
df_impute = pd.concat([df_num_impute,df_cat_impute],axis=1)

df = df_impute.copy()
#checking for null values
df.isnull().sum()

student_id                     0
age                            0
study_hours_per_day            0
deep_work_sessions             0
assignment_completion_rate     0
attendance_percentage          0
social_media_hours             0
doomscrolling_before_sleep     0
notification_distractions      0
ai_tool_usage_hours            0
gaming_hours                   0
stress_level                   0
motivation_level               0
focus_score                    0
procrastination_index          0
sleep_hours                    0
caffeine_intake                0
physical_activity_hours        0
internet_quality               0
family_support                 0
financial_stress               0
productivity_after_midnight    0
revision_efficiency            0
burnout_risk                   0
consistency_score              0
final_exam_score               0
gender                         0
city_type                      0
mental_state                   0
learning_style                 0
career_goal                    0
performance_category           0
dtype: int64

### Question 5: Label Encoding (3 Marks)
Use `LabelEncoder` from `sklearn.preprocessing` to encode all categorical columns into numerical values. Print the first 5 rows of the updated DataFrame.

**Hint:** Loop through the categorical columns and apply `.fit_transform()`.

**Expected Output:**
```
A pandas DataFrame head with all columns containing numerical values.
```

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

#Dataframe for categorical columns
cat = df.select_dtypes(exclude="number").columns

#Loop through the categorical columns
for i in cat:
  df[i] = le.fit_transform(df[i])
df.head()

,student_id,age,study_hours_per_day,deep_work_sessions,assignment_completion_rate,attendance_percentage,social_media_hours,doomscrolling_before_sleep,notification_distractions,ai_tool_usage_hours,...,revision_efficiency,burnout_risk,consistency_score,final_exam_score,gender,city_type,mental_state,learning_style,career_goal,performance_category
0,0.0,21.0,3.2,7.0,100.0,70.0,3.8,0.0,107.0,0.6,...,1.0,10.0,3.0,32.0,0,1,0,0,2,1
1,1.0,19.0,3.9,2.0,46.0,70.0,2.6,1.0,93.0,1.5,...,10.0,4.0,6.0,59.0,0,1,1,1,1,2
2,2.0,16.0,4.3,7.0,54.0,57.0,4.3,1.0,82.0,0.5,...,9.0,8.0,1.0,34.0,0,2,1,3,2,1
3,3.0,19.0,5.3,1.0,78.0,90.0,1.7,0.0,27.0,1.4,...,7.0,9.0,10.0,60.0,1,1,1,2,3,2
4,4.0,17.0,4.1,3.0,100.0,81.0,2.6,0.0,8.0,1.3,...,10.0,7.0,9.0,77.0,0,2,3,3,3,0

### Question 6: Feature and Target Separation (3 Marks)
Separate the features `X` and the target `y` (assuming 'performance_category' is the target). Print the shapes of `X` and `y`.

**Expected Output:**
```
Shapes of X and y (e.g., (n_samples, n_features) and (n_samples,)).
```

In [38]:
X = df.drop('performance_category',axis=1)
Y = df['performance_category']
X.shape , Y.shape

((3000, 31), (3000,))

### Question 7: Train-Test Split (3 Marks)
Split the data into training and testing sets with a test size of 20% and `random_state=42`. Print the shapes of `X_train` and `X_test`.

**Expected Output:**
```
Shapes of X_train and X_test.
```

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((2400, 31), (600, 31))

### Question 8: Feature Scaling (3 Marks)
Scale the features using `MinMaxScaler` from `sklearn.preprocessing`. Fit on `X_train` and transform both `X_train` and `X_test`. Print the minimum and maximum values of the scaled `X_train`.

In [48]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

#using .fit_transform
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#printing min and max value
print(f'Minimum value of scaled X_train is {X_train_scaled.min()}')
print(f'Maximum value of scaled X_train is {X_train_scaled.max()}')

Minimum value of scaled X_train is 0.0
Maximum value of scaled X_train is 1.0

### Question 9: Decision Tree Classifier (5 Marks)
Initialize and train a `DecisionTreeClassifier` with `random_state=42`. Make predictions on the test set and print the accuracy score.

**Expected Output:**
```
A numerical value representing the accuracy score.
```

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
dt = DecisionTreeClassifier(random_state = 42)

#Decision Tree fitting and predicting
dt.fit(X_train_scaled,Y_train)
y_pred = dt.predict(X_test_scaled)

#printing the Accuracy score
a = accuracy_score(Y_test,y_pred)
print(f'Accuracy Score is {a}')

Accuracy Score is 1.0

### Question 10: Feature Importance (4 Marks)
Extract the feature importances from the trained Decision Tree model. Print a dictionary or a pandas Series mapping feature names to their importance scores.

**Hint:** Access `.feature_importances_` on the trained model and combine it with `X.columns`.

**Expected Output:**
```
A mapping of feature names to their importance scores.
```

In [47]:
feature_importances = pd.Series(data=dt.feature_importances_, index=X_train.columns).sort_values(ascending=False)

#Pandas Series
print("Feature Importances:")
print(feature_importances)

Feature Importances:
final_exam_score               1.0
age                            0.0
student_id                     0.0
deep_work_sessions             0.0
assignment_completion_rate     0.0
attendance_percentage          0.0
study_hours_per_day            0.0
doomscrolling_before_sleep     0.0
notification_distractions      0.0
ai_tool_usage_hours            0.0
gaming_hours                   0.0
stress_level                   0.0
motivation_level               0.0
focus_score                    0.0
social_media_hours             0.0
procrastination_index          0.0
sleep_hours                    0.0
physical_activity_hours        0.0
caffeine_intake                0.0
family_support                 0.0
financial_stress               0.0
productivity_after_midnight    0.0
internet_quality               0.0
revision_efficiency            0.0
burnout_risk                   0.0
consistency_score              0.0
gender                         0.0
city_type                      0.0
mental_state                   0.0
learning_style                 0.0
career_goal                    0.0
dtype: float64